### ISSUE TITLE
Rendering issues in phcode.dev

### ISSUE THREAD

**Issue by abose** [MerryPanda/brackets-productivity-project-files-search#1]
Hi,

 https://phcode.dev has introduced extension support recently, and looks like the extension has a layout issue:
![image](https://user-images.githubusercontent.com/5336369/212246183-6f62d1f9-3258-4a41-8a23-a79fa815afd2.png)

### To debug the extension in phcode:
 Since extension support is fairly recent, the process has yet to be fine-tuned. Follow these steps for now to access dev builds:
1. goto https://staging.phcode.dev/devEnable.html and enable staging.phcode.dev
2. goto https://staging.phcode.dev/
3. Download the extension
4. select menu `debug > open virtual file system`
5. open `/fs/app/extensions/user/<extension>`
6. change the code and reload page to debug

Best,
Arun.

**Comment by MerryPanda** [comment]
Thanks for info, I'll take a look

**Comment by abose** [comment]
Issue fixed. Closing.
Thanks!
